function tauri() {
  return window.__TAURI__ || {};
}

function invoke(command, args = {}) {
  const core = tauri().core;
  if (!core?.invoke) return Promise.reject(new Error('Tauri runtime is not available'));
  return core.invoke(command, args);
}

const updaterCheck = () => tauri().updater?.check?.();
const relaunch = () => tauri().process?.relaunch?.();
const enableAutostart = () => tauri().autostart?.enable?.();
const disableAutostart = () => tauri().autostart?.disable?.();
const isAutostartEnabled = () => tauri().autostart?.isEnabled?.() || Promise.resolve(false);

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

let accounts = [];
let selectedPlatform = 'codex';
let selectedAuthTab = 'session';
let deleteTargetId = null;
let quickSelectedIndex = 0;
let installChannel = 'unknown';
let settings = { autoUpdate: true, notifications: true };

const PROVIDERS = {
  codex: {
    label: 'OpenAI / Codex',
    short: 'OpenAI',
    initial: 'O',
    sessionTitle: 'Import your active Codex session',
    sessionDesc: 'Sign in through Codex using ChatGPT first. SwitchCraft imports the local OAuth session generated by the official client and stores its own copy in the OS credential vault. API keys are not used by this flow.',
    path: '~/.codex/auth.json',
  },
  gemini: {
    label: 'Google / Gemini',
    short: 'Google',
    initial: 'G',
    sessionTitle: 'Import your active Google session',
    sessionDesc: 'Start Gemini CLI and choose Sign in with Google first. SwitchCraft imports oauth_creds.json and tracks the active email from google_accounts.json so both files can be changed together.',
    path: '~/.gemini/oauth_creds.json + google_accounts.json',
  },
  claude: {
    label: 'Anthropic / Claude',
    short: 'Anthropic',
    initial: 'C',
    sessionTitle: 'Import your active Claude Code session',
    sessionDesc: 'SwitchCraft v1.1 supports Claude Code file-backed credentials. On macOS, Claude normally uses Keychain; use its file fallback or an isolated CLAUDE_CONFIG_DIR profile until native Claude-keychain switching is implemented.',
    path: '~/.claude/.credentials.json',
  },
};

const platformSections = $('#platform-sections');
const emptyState = $('#empty-state');
const modalOverlay = $('#modal-overlay');
const confirmOverlay = $('#confirm-overlay');
const quickOverlay = $('#quick-overlay');
const quickSearchInput = $('#quick-search-input');
const quickList = $('#quick-list');
const inputName = $('#input-name');
const inputCreds = $('#input-creds');
const inputEmail = $('#input-email');
const inputPlan = $('#input-plan');
const inputFiveRemaining = $('#input-five-remaining');
const inputWeeklyRemaining = $('#input-weekly-remaining');
const primaryAccountAction = $('#btn-primary-account-action');
const toastEl = $('#toast');
const toastMessage = $('#toast-message');

async function initApp() {
  setupEventListeners();
  updateShortcutLabel();
  await Promise.all([loadVersion(), loadAccounts(), loadSettings()]);
  await loadInstallChannel();
  if (settings.autoUpdate && installChannel !== 'msi') {
    setTimeout(() => checkForUpdates(true), 1800);
  }
}

document.readyState === 'loading'
  ? document.addEventListener('DOMContentLoaded', initApp)
  : initApp();

async function loadVersion() {
  try {
    $('#version-number').textContent = `v${await invoke('get_app_version')}`;
  } catch {
    $('#version-number').textContent = 'v1.2.0';
  }
}

async function loadInstallChannel() {
  try {
    installChannel = await invoke('get_install_channel');
  } catch {
    installChannel = 'unknown';
  }

  if (installChannel === 'msi') {
    const toggle = $('#toggle-autoupdate');
    toggle.checked = false;
    toggle.disabled = true;
    toggle.title = 'MSI installations use MSI-to-MSI updates from GitHub Releases';
  }
}

async function loadAccounts() {
  try {
    accounts = await invoke('get_accounts');
  } catch (error) {
    accounts = [];
    toast(`Could not load accounts: ${error}`, true);
  }
  renderAccounts();
  await refreshSecuritySummary();
}

function securityLabel(state) {
  if (state === 'secure') return ['Secure vault', ''];
  if (state === 'legacy_plaintext') return ['Legacy storage', 'security-dot--legacy'];
  return ['Secret missing', 'security-dot--missing'];
}

function usageLevel(remaining) {
  if (remaining >= 60) return 'ok';
  if (remaining >= 30) return 'warn';
  return 'critical';
}

function usageRow(label, remaining) {
  if (remaining === null || remaining === undefined) return '';
  const value = Math.max(0, Math.min(100, Number(remaining)));
  return `
    <div class="usage-line">
      <span class="usage-label">${label}</span>
      <div class="usage-track"><div class="usage-fill usage-fill--${usageLevel(value)}" style="width:${value}%"></div></div>
      <span class="usage-value">${value}%</span>
    </div>`;
}

function renderAccounts() {
  let total = 0;

  Object.keys(PROVIDERS).forEach((platform) => {
    const list = $(`[data-list="${platform}"]`);
    const count = $(`[data-count="${platform}"]`);
    const providerAccounts = accounts.filter((account) => account.platform === platform);
    total += providerAccounts.length;
    count.textContent = `${providerAccounts.length} account${providerAccounts.length === 1 ? '' : 's'}`;

    if (!providerAccounts.length) {
      list.innerHTML = '<div class="account-empty">No profiles imported for this provider</div>';
      return;
    }

    list.innerHTML = providerAccounts.map((account) => {
      const provider = PROVIDERS[account.platform];
      const [securityText, securityClass] = securityLabel(account.security_state);
      const usage = account.usage || {};
      const usageHtml = usageRow('5 hours', usage.five_hour_remaining_pct) + usageRow('Weekly', usage.weekly_remaining_pct);
      const identity = account.email || account.targets?.[0] || provider.label;
      const plan = usage.plan_name ? ` · ${escapeHtml(usage.plan_name)}` : '';

      return `
        <article class="account-card ${account.is_active ? 'active' : ''}" data-account-id="${account.id}">
          <div class="account-avatar">${provider.initial}</div>
          <div class="account-main">
            <div class="account-topline">
              <span class="account-name">${escapeHtml(account.name)}</span>
              ${account.is_active ? '<span class="active-label">Active</span>' : ''}
            </div>
            <div class="account-subline">
              <span class="security-dot ${securityClass}"></span>
              <span>${securityText}${plan}</span>
              <span>·</span>
              <span>${escapeHtml(identity)}</span>
            </div>
            ${usageHtml ? `<div class="usage-block">${usageHtml}</div>` : ''}
          </div>
          <div class="account-actions">
            <button class="btn ${account.is_active ? 'btn--outline' : 'btn--gold'} btn--sm switch-btn" data-switch="${account.id}" ${account.is_active ? 'disabled' : ''}>${account.is_active ? 'Active' : 'Switch'}</button>
            <button class="icon-btn icon-btn--danger" data-delete="${account.id}" title="Remove profile" aria-label="Remove ${escapeHtml(account.name)}">
              <svg viewBox="0 0 20 20" width="14" height="14" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4.5 6h11M8 6V4.5h4V6m2 0-.6 10H6.6L6 6"/></svg>
            </button>
          </div>
        </article>`;
    }).join('');
  });

  platformSections.classList.toggle('hidden', total === 0);
  emptyState.classList.toggle('hidden', total !== 0);

  $$('[data-switch]').forEach((button) => button.addEventListener('click', () => switchAccount(button.dataset.switch)));
  $$('[data-delete]').forEach((button) => button.addEventListener('click', () => openDeleteConfirmation(button.dataset.delete)));
}

async function switchAccount(id) {
  const account = accounts.find((item) => item.id === id);
  if (!account || account.is_active) return;

  const buttons = $$(`[data-switch="${id}"]`);
  buttons.forEach((button) => { button.disabled = true; button.textContent = 'Switching…'; });

  try {
    await invoke('switch_account', { id });
    if (settings.notifications) toast(`${account.name} is now active in ${PROVIDERS[account.platform].short}`);
    closeQuickSwitch();
    await loadAccounts();
  } catch (error) {
    toast(`Switch failed: ${error}`, true);
    buttons.forEach((button) => { button.disabled = false; button.textContent = 'Switch'; });
  }
}

function openDeleteConfirmation(id) {
  deleteTargetId = id;
  const account = accounts.find((item) => item.id === id);
  if (!account) return;
  $('#confirm-message').textContent = `Remove “${account.name}” from SwitchCraft? This deletes the protected SwitchCraft copy, but does not sign out the provider's currently active client session.`;
  confirmOverlay.classList.remove('hidden');
}

async function deleteAccount() {
  if (!deleteTargetId) return;
  try {
    await invoke('delete_account', { id: deleteTargetId });
    confirmOverlay.classList.add('hidden');
    deleteTargetId = null;
    toast('Profile removed from SwitchCraft');
    await loadAccounts();
  } catch (error) {
    toast(`Could not remove profile: ${error}`, true);
  }
}

function openModal() {
  selectedPlatform = 'codex';
  selectedAuthTab = 'session';
  inputName.value = '';
  inputCreds.value = '';
  inputEmail.value = '';
  inputPlan.value = '';
  inputFiveRemaining.value = '';
  inputWeeklyRemaining.value = '';
  $$('.provider-pick').forEach((item) => item.classList.toggle('active', item.dataset.pick === 'codex'));
  selectAuthTab('session');
  updateProviderModal();
  modalOverlay.classList.remove('hidden');
  inputName.focus();
}

function closeModal() {
  modalOverlay.classList.add('hidden');
}

function selectAuthTab(tab) {
  selectedAuthTab = tab;
  $$('.auth-tab').forEach((item) => item.classList.toggle('active', item.dataset.tab === tab));
  $$('.auth-content').forEach((item) => item.classList.toggle('active', item.id === `tab-content-${tab}`));
  primaryAccountAction.textContent = tab === 'session' ? 'Import active session' : 'Save protected profile';
}

function updateProviderModal() {
  const provider = PROVIDERS[selectedPlatform];
  $('#session-title').textContent = provider.sessionTitle;
  $('#session-desc').textContent = provider.sessionDesc;
  $('#session-path').textContent = provider.path;
  $('#email-group').classList.toggle('hidden', selectedPlatform !== 'gemini');
}

function usagePayload() {
  const five = inputFiveRemaining.value === '' ? null : Math.max(0, Math.min(100, Number(inputFiveRemaining.value)));
  const weekly = inputWeeklyRemaining.value === '' ? null : Math.max(0, Math.min(100, Number(inputWeeklyRemaining.value)));
  const planName = inputPlan.value.trim();

  if (!planName && five === null && weekly === null) return null;
  return {
    plan_name: planName,
    five_hour_remaining_pct: five,
    weekly_remaining_pct: weekly,
    five_hour_reset_at: null,
    weekly_reset_at: null,
    source: 'manual',
    observed_at: new Date().toISOString(),
  };
}

async function saveUsage(accountId) {
  const usage = usagePayload();
  if (!usage) return;
  await invoke('update_usage', { id: accountId, usage });
}

async function handlePrimaryAccountAction() {
  const name = inputName.value.trim();
  if (!name) {
    toast('Enter a profile name', true);
    inputName.focus();
    return;
  }

  primaryAccountAction.disabled = true;
  try {
    let account;
    if (selectedAuthTab === 'session') {
      account = await invoke('import_current_account', { name, platform: selectedPlatform });
    } else {
      const raw = inputCreds.value.trim();
      if (!raw) throw new Error('Paste the credential JSON first');
      let credentials;
      try { credentials = JSON.parse(raw); } catch { throw new Error('Credential JSON is invalid'); }

      const email = selectedPlatform === 'gemini' ? inputEmail.value.trim() : null;
      if (selectedPlatform === 'gemini' && !email) throw new Error('Gemini profiles added manually require the Google account email');
      account = await invoke('add_account', { name, platform: selectedPlatform, credentials, email: email || null });
    }

    await saveUsage(account.id);
    closeModal();
    toast(`${name} added securely`);
    await loadAccounts();
  } catch (error) {
    toast(String(error), true);
  } finally {
    primaryAccountAction.disabled = false;
  }
}

async function refreshSecuritySummary() {
  try {
    const summary = await invoke('get_security_summary');
    const label = summary.legacy_accounts > 0
      ? `${summary.secure_accounts} secure · ${summary.legacy_accounts} legacy pending migration`
      : `${summary.secure_accounts} protected profile${summary.secure_accounts === 1 ? '' : 's'}`;
    $('#security-summary').textContent = label;
  } catch {
    $('#security-summary').textContent = 'Vault status unavailable';
  }
}

async function restorePreviousSession(platform) {
  try {
    await invoke('restore_last_session', { platform });
    toast(`Previous ${PROVIDERS[platform].short} session restored`);
    await loadAccounts();
  } catch (error) {
    toast(`Restore failed: ${error}`, true);
  }
}

function openQuickSwitch() {
  if (!accounts.length) {
    toast('Add an account before using Quick Switch');
    return;
  }
  quickSelectedIndex = 0;
  quickSearchInput.value = '';
  renderQuickList();
  quickOverlay.classList.remove('hidden');
  setTimeout(() => quickSearchInput.focus(), 0);
}

function closeQuickSwitch() {
  quickOverlay.classList.add('hidden');
}

function filteredQuickAccounts() {
  const query = quickSearchInput.value.trim().toLowerCase();
  if (!query) return accounts;
  return accounts.filter((account) => `${account.name} ${account.email || ''} ${PROVIDERS[account.platform].label}`.toLowerCase().includes(query));
}

function renderQuickList() {
  const filtered = filteredQuickAccounts();
  if (quickSelectedIndex >= filtered.length) quickSelectedIndex = Math.max(0, filtered.length - 1);
  if (!filtered.length) {
    quickList.innerHTML = '<div class="quick-empty">No matching accounts</div>';
    return;
  }

  quickList.innerHTML = filtered.map((account, index) => {
    const provider = PROVIDERS[account.platform];
    const weekly = account.usage?.weekly_remaining_pct;
    return `
      <button class="quick-item ${index === quickSelectedIndex ? 'selected' : ''}" data-quick-id="${account.id}" type="button">
        <span class="quick-item-logo">${provider.initial}</span>
        <span class="quick-item-copy"><strong>${escapeHtml(account.name)}</strong><span>${escapeHtml(account.email || provider.label)}</span></span>
        <span class="quick-item-meta">${account.is_active ? 'ACTIVE' : weekly !== null && weekly !== undefined ? `${weekly}% WK` : 'SWITCH'}</span>
      </button>`;
  }).join('');

  $$('[data-quick-id]').forEach((item) => item.addEventListener('click', () => switchAccount(item.dataset.quickId)));
}

function moveQuickSelection(delta) {
  const filtered = filteredQuickAccounts();
  if (!filtered.length) return;
  quickSelectedIndex = (quickSelectedIndex + delta + filtered.length) % filtered.length;
  renderQuickList();
  $('.quick-item.selected')?.scrollIntoView({ block: 'nearest' });
}

function activateQuickSelection() {
  const filtered = filteredQuickAccounts();
  const account = filtered[quickSelectedIndex];
  if (account && !account.is_active) switchAccount(account.id);
}

async function loadSettings() {
  try { $('#toggle-autostart').checked = await isAutostartEnabled(); } catch { $('#toggle-autostart').checked = false; }
  try {
    const stored = localStorage.getItem('switchcraft_settings');
    if (stored) settings = { ...settings, ...JSON.parse(stored) };
  } catch { /* keep defaults */ }
  $('#toggle-autoupdate').checked = settings.autoUpdate;
  $('#toggle-notifications').checked = settings.notifications;
}

function saveSettings() {
  settings.autoUpdate = $('#toggle-autoupdate').checked;
  settings.notifications = $('#toggle-notifications').checked;
  localStorage.setItem('switchcraft_settings', JSON.stringify(settings));
}

async function openLatestReleaseForMsi() {
  toast('MSI installation detected. Opening the latest MSI release…');
  await invoke('open_browser_url', {
    url: 'https://github.com/dannymaaz/SwitchCraft/releases/latest',
  });
}

async function checkForUpdates(silent = false) {
  if (installChannel === 'msi') {
    if (!silent) {
      try {
        await openLatestReleaseForMsi();
      } catch (error) {
        toast(`Could not open the latest release: ${error}`, true);
      }
    }
    return;
  }

  try {
    const checkFn = updaterCheck();
    if (!checkFn) {
      if (!silent) toast('Updater is not available in this build');
      return;
    }
    const update = await checkFn;
    if (update) {
      $('#update-banner').classList.remove('hidden');
      if (!silent) toast('A new SwitchCraft version is available');
    } else if (!silent) {
      toast('SwitchCraft is up to date');
    }
  } catch (error) {
    if (!silent) toast(`Update check failed: ${error}`, true);
  }
}

async function installUpdate() {
  if (installChannel === 'msi') {
    try {
      await openLatestReleaseForMsi();
    } catch (error) {
      toast(`Could not open the latest release: ${error}`, true);
    }
    return;
  }

  try {
    const update = await updaterCheck();
    if (!update) return;
    toast('Downloading signed update…');
    await update.downloadAndInstall();
    if (relaunch) await relaunch();
  } catch (error) {
    toast(`Update failed: ${error}`, true);
  }
}

function navigateTo(page) {
  $$('.nav-btn').forEach((button) => button.classList.toggle('active', button.dataset.page === page));
  $$('.page').forEach((section) => section.classList.toggle('active', section.id === `page-${page}`));
}

let toastTimer;
function toast(message, isError = false) {
  clearTimeout(toastTimer);
  toastMessage.textContent = message;
  toastEl.classList.toggle('error', isError);
  toastEl.classList.remove('hidden');
  requestAnimationFrame(() => toastEl.classList.add('visible'));
  toastTimer = setTimeout(() => {
    toastEl.classList.remove('visible');
    setTimeout(() => toastEl.classList.add('hidden'), 180);
  }, 3300);
}

function escapeHtml(value) {
  const node = document.createElement('div');
  node.textContent = String(value ?? '');
  return node.innerHTML;
}

function updateShortcutLabel() {
  const isMac = /Mac|iPhone|iPad/.test(navigator.platform);
  $('#btn-quick-switch kbd').textContent = isMac ? '⌘ K' : 'Ctrl K';
}

function setupEventListeners() {
  $('#btn-minimize').addEventListener('click', () => invoke('minimize_window').catch(() => {}));
  $('#btn-close').addEventListener('click', () => invoke('hide_window').catch(() => {}));
  $$('.nav-btn').forEach((button) => button.addEventListener('click', () => navigateTo(button.dataset.page)));

  $('#btn-add-account').addEventListener('click', openModal);
  $('#btn-add-first').addEventListener('click', openModal);
  $('#btn-modal-close').addEventListener('click', closeModal);
  $('#btn-cancel').addEventListener('click', closeModal);
  primaryAccountAction.addEventListener('click', handlePrimaryAccountAction);
  modalOverlay.addEventListener('click', (event) => { if (event.target === modalOverlay) closeModal(); });

  $$('.provider-pick').forEach((button) => button.addEventListener('click', () => {
    selectedPlatform = button.dataset.pick;
    $$('.provider-pick').forEach((item) => item.classList.toggle('active', item === button));
    updateProviderModal();
  }));
  $$('.auth-tab').forEach((button) => button.addEventListener('click', () => selectAuthTab(button.dataset.tab)));

  $('#btn-confirm-cancel').addEventListener('click', () => confirmOverlay.classList.add('hidden'));
  $('#btn-confirm-delete').addEventListener('click', deleteAccount);
  confirmOverlay.addEventListener('click', (event) => { if (event.target === confirmOverlay) confirmOverlay.classList.add('hidden'); });

  $('#btn-quick-switch').addEventListener('click', openQuickSwitch);
  quickOverlay.addEventListener('click', (event) => { if (event.target === quickOverlay) closeQuickSwitch(); });
  quickSearchInput.addEventListener('input', () => { quickSelectedIndex = 0; renderQuickList(); });

  $$('[data-restore]').forEach((button) => button.addEventListener('click', () => restorePreviousSession(button.dataset.restore)));

  $('#toggle-autostart').addEventListener('change', async (event) => {
    try {
      if (event.target.checked) await enableAutostart(); else await disableAutostart();
      toast(event.target.checked ? 'Launch at startup enabled' : 'Launch at startup disabled');
    } catch (error) {
      event.target.checked = !event.target.checked;
      toast(`Autostart error: ${error}`, true);
    }
  });
  $('#toggle-autoupdate').addEventListener('change', saveSettings);
  $('#toggle-notifications').addEventListener('change', saveSettings);
  $('#btn-manual-update').addEventListener('click', () => checkForUpdates(false));
  $('#btn-update').addEventListener('click', installUpdate);
  $('#btn-github').addEventListener('click', () => invoke('open_browser_url', { url: 'https://github.com/dannymaaz/SwitchCraft' }).catch((error) => toast(String(error), true)));

  document.addEventListener('keydown', (event) => {
    if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') {
      event.preventDefault();
      quickOverlay.classList.contains('hidden') ? openQuickSwitch() : closeQuickSwitch();
      return;
    }

    if (!quickOverlay.classList.contains('hidden')) {
      if (event.key === 'ArrowDown') { event.preventDefault(); moveQuickSelection(1); return; }
      if (event.key === 'ArrowUp') { event.preventDefault(); moveQuickSelection(-1); return; }
      if (event.key === 'Enter') { event.preventDefault(); activateQuickSelection(); return; }
    }

    if (event.key === 'Escape') {
      if (!quickOverlay.classList.contains('hidden')) closeQuickSwitch();
      else if (!modalOverlay.classList.contains('hidden')) closeModal();
      else if (!confirmOverlay.classList.contains('hidden')) confirmOverlay.classList.add('hidden');
    }
  });
}